version: '3.8'
services:
  postgres:
    environment:
      # Use following command to access psql
      # docker run -it --rm --network alert_badger_default postgres psql -h postgres -U alert_badger_app alert_badger_development
      POSTGRES_USER: alert_badger_app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: alert_badger_development

  alert_badger:
    stdin_open: true
    tty: true
    volumes:
      # https://docs.docker.com/docker-for-mac/osxfs-caching/#semantics
      - .:/alert_badger:cached
    environment:
      # DATABASE_URL:       postgresql://alert_badger_app:password@postgres:5432/alert_badger_development
      RAILS_ENV:          'development'
      RACK_ENV:           'development'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    ports:
      - "12345:80"
    environment:
      - GUNICORN_THREADS=1
      - PGADMIN_DEFAULT_EMAIL=bittu@test.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - postgres
      
volumes:
  postgres:
    driver: local
  pg_admin:
